sudo: required
dist: trusty

script:
  - bash -xve ./test/travis_ros_install.bash
  - source ~/catkin_ws/devel/setup.bash
  - bash -xve ./test/travis_package_make.bash
  - sudo chmod 777 /dev/
  - rostest pimouse_ros pimouse.launch
